"""Add market raw tables for inquiries, revenue and settlement

Revision ID: 31e557010b9a
Revises: a4f18a26199f
Create Date: 2025-12-27 17:55:35.990179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '31e557010b9a'
down_revision: Union[str, None] = 'a4f18a26199f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    pass


def downgrade_source() -> None:
    pass


def upgrade_dropship() -> None:
    pass


def downgrade_dropship() -> None:
    pass


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_inquiry_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['market_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'account_id', 'inquiry_id', name='uq_market_inquiry_raw_account_inquiry')
    )
    op.create_table('market_revenue_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('sale_type', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['market_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'account_id', 'order_id', 'sale_type', name='uq_market_revenue_raw_account_order_type')
    )
    op.create_table('market_settlement_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('recognition_year_month', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['market_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'account_id', 'recognition_year_month', name='uq_market_settlement_raw_account_month')
    )
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_settlement_raw')
    op.drop_table('market_revenue_raw')
    op.drop_table('market_inquiry_raw')
    # ### end Alembic commands ###
