"""add product_options table

Revision ID: 373f92327923
Revises: 8dc968ed9700
Create Date: 2025-12-27 18:12:10.447989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '373f92327923'
down_revision: Union[str, None] = '8dc968ed9700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    # No changes for source engine
    pass


def downgrade_source() -> None:
    # No changes for source engine
    pass


def upgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('option_name', sa.Text(), nullable=False),
    sa.Column('option_value', sa.Text(), nullable=False),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('external_option_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_options')
    # ### end Alembic commands ###


def upgrade_market() -> None:
    # No changes for market engine
    pass


def downgrade_market() -> None:
    # No changes for market engine
    pass
