"""add_sourcing_candidate_and_advanced_fields

Revision ID: 3dfc3670eb97
Revises: 7b63f2cccd27
Create Date: 2025-12-15 19:32:33.625661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

revision: str = '3dfc3670eb97'
down_revision: Union[str, None] = '7b63f2cccd27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcing_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('supplier_item_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('supply_price', sa.Integer(), nullable=False),
    sa.Column('source_strategy', sa.Text(), nullable=False),
    sa.Column('benchmark_product_id', sa.UUID(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('seasonal_score', sa.Float(), nullable=True),
    sa.Column('margin_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('spec_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seo_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_event', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_product_id'], ['benchmark_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('benchmark_products', sa.Column('review_summary', sa.Text(), nullable=True))
    op.add_column('benchmark_products', sa.Column('pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benchmark_products', 'pain_points')
    op.drop_column('benchmark_products', 'review_summary')
    op.drop_table('sourcing_candidates')
    # ### end Alembic commands ###
