"""Add analytics sync state table

Revision ID: 558e2836999e
Revises: 2108110b02c6
Create Date: 2025-12-31 16:21:55.366587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '558e2836999e'
down_revision: Union[str, None] = '2108110b02c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_sync_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.Text(), nullable=False),
    sa.Column('last_sync_id', sa.UUID(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_type')
    )
    # ### end Alembic commands ###


def downgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics_sync_state')
    # ### end Alembic commands ###


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
