"""add product_option_id to order_items

Revision ID: 62969964c2c8
Revises: 373f92327923
Create Date: 2025-12-27 18:22:39.570259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '62969964c2c8'
down_revision: Union[str, None] = '373f92327923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    pass


def downgrade_source() -> None:
    pass


def upgrade_dropship() -> None:
    pass


def downgrade_dropship() -> None:
    pass


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_option_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_option_id')
    # ### end Alembic commands ###
