"""update_embedding_dimension

Revision ID: 801fa2f3912e
Revises: dbaa35acd490
Create Date: 2025-12-19 19:53:46.126250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '801fa2f3912e'
down_revision: Union[str, None] = 'dbaa35acd490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_dropship() -> None:
    op.execute("ALTER TABLE embeddings ALTER COLUMN embedding TYPE vector(768)")


def downgrade_dropship() -> None:
    op.execute("ALTER TABLE embeddings ALTER COLUMN embedding TYPE vector(3)")


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
