"""Add PR-6 sync and order models

Revision ID: 8a85fe83c73f
Revises: 9f2d1c77b8b0
Create Date: 2025-12-31 15:43:24.564837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

revision: str = '8a85fe83c73f'
down_revision: Union[str, None] = '9f2d1c77b8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_cursors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'channel', name='uq_sync_cursors_vendor_channel')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=False),
    sa.Column('write_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('rate_limited_count', sa.Integer(), nullable=False),
    sa.Column('cursor_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cursor_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_run_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_run_errors')
    op.drop_table('sync_runs')
    op.drop_table('sync_cursors')
    # ### end Alembic commands ###


def upgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM embeddings")
    op.alter_column('embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.alter_column('products', 'coupang_fallback_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('products_supplier_item_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('sourcing_candidates_benchmark_product_id_fkey', 'sourcing_candidates', type_='foreignkey')
    op.drop_constraint('sourcing_recommendations_product_id_fkey', 'sourcing_recommendations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('sourcing_recommendations_product_id_fkey', 'sourcing_recommendations', 'products', ['product_id'], ['id'])
    op.create_foreign_key('sourcing_candidates_benchmark_product_id_fkey', 'sourcing_candidates', 'benchmark_products', ['benchmark_product_id'], ['id'])
    op.create_foreign_key('products_supplier_item_id_fkey', 'products', 'supplier_item_raw', ['supplier_item_id'], ['id'])
    op.alter_column('products', 'coupang_fallback_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qna_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('vendor_thread_id', sa.Text(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('customer_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_thread_id')
    )
    op.create_table('qna_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('vendor_message_id', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['qna_threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_message_id')
    )
    op.alter_column('adaptive_policy_events', 'policy_version',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('adaptive_policy_events', 'top_rejection_reasons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('market_inquiry_raw', 'send_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint('market_listings_product_id_fkey', 'market_listings', type_='foreignkey')
    op.add_column('order_items', sa.Column('vendor_item_id', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('vendor_sku', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('status', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uq_order_items_order_vendor_item', 'order_items', ['order_id', 'vendor_item_id'])
    op.drop_column('order_items', 'external_item_id')
    op.add_column('orders', sa.Column('vendor_order_id', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('marketplace', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('buyer_hash', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'orders', ['vendor_order_id'])
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'raw')
    op.drop_column('orders', 'ordered_at')
    op.drop_column('orders', 'totals')
    op.drop_column('orders', 'buyer_hash')
    op.drop_column('orders', 'marketplace')
    op.drop_column('orders', 'vendor_order_id')
    op.add_column('order_items', sa.Column('external_item_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_order_items_order_vendor_item', 'order_items', type_='unique')
    op.drop_column('order_items', 'raw')
    op.drop_column('order_items', 'status')
    op.drop_column('order_items', 'vendor_sku')
    op.drop_column('order_items', 'vendor_item_id')
    op.create_foreign_key('market_listings_product_id_fkey', 'market_listings', 'products', ['product_id'], ['id'])
    op.alter_column('market_inquiry_raw', 'send_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('adaptive_policy_events', 'top_rejection_reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('adaptive_policy_events', 'policy_version',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('qna_messages')
    op.drop_table('qna_threads')
    # ### end Alembic commands ###
