"""add ai_suggested_answer to market_inquiry_raw

Revision ID: 8dc968ed9700
Revises: cc3fe0dcbee2
Create Date: 2025-12-27 18:05:47.573262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8dc968ed9700'
down_revision: Union[str, None] = 'cc3fe0dcbee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark_collect_jobs', sa.Column('category_url', sa.Text(), nullable=True))
    op.add_column('benchmark_collect_jobs', sa.Column('processed_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('benchmark_collect_jobs', sa.Column('total_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('market_inquiry_raw', sa.Column('ai_suggested_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_inquiry_raw', 'ai_suggested_answer')
    op.drop_column('benchmark_collect_jobs', 'total_count')
    op.drop_column('benchmark_collect_jobs', 'processed_count')
    op.drop_column('benchmark_collect_jobs', 'category_url')
    # ### end Alembic commands ###
