"""add autonomy models

Revision ID: 96491916c27b
Revises: e71f7fbc1788
Create Date: 2025-12-31 17:49:44.903572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '96491916c27b'
down_revision: Union[str, None] = 'e71f7fbc1788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autonomy_decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('segment_key', sa.Text(), nullable=False),
    sa.Column('tier_used', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('expected_margin', sa.Float(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autonomy_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_key', sa.Text(), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('category_code', sa.Text(), nullable=True),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('lifecycle_stage', sa.Text(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('config_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_key')
    )
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autonomy_policies')
    op.drop_table('autonomy_decision_logs')
    # ### end Alembic commands ###
