"""Add market schema and credentials

Revision ID: 9a026dcf6d52
Revises: 
Create Date: 2025-12-15 19:03:01.631731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

revision: str = '9a026dcf6d52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'name', name='uq_market_accounts_code_name')
    )
    op.create_table('supplier_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('supplier_order_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_order_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['market_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'account_id', 'order_id', name='uq_market_order_raw_account_order')
    )
    op.create_table('market_product_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('market_item_id', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['market_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'account_id', 'market_item_id', name='uq_market_product_raw_account_item')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_item_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_item_id'], ['supplier_item_raw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('market_account_id', sa.UUID(), nullable=False),
    sa.Column('market_item_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_account_id'], ['market_accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_account_id', 'market_item_id', name='uq_market_listings_account_item')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_order_id', sa.UUID(), nullable=True),
    sa.Column('supplier_order_id', sa.UUID(), nullable=True),
    sa.Column('order_number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('recipient_name', sa.Text(), nullable=True),
    sa.Column('recipient_phone', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_order_id'], ['market_order_raw.id'], ),
    sa.ForeignKeyConstraint(['supplier_order_id'], ['supplier_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    # op.drop_table('embedding_test')
    op.add_column('supplier_accounts', sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_accounts', 'credentials')
    # op.create_table('embedding_test',
    # sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='embedding_test_pkey')
    # )
    op.drop_table('orders')
    op.drop_table('market_listings')
    op.drop_table('products')
    op.drop_table('market_product_raw')
    op.drop_table('market_order_raw')
    op.drop_table('supplier_orders')
    op.drop_table('market_accounts')
    # ### end Alembic commands ###
