"""add_option_recommendations_to_sourcing

Revision ID: af4d6b1b4ef0
Revises: 62969964c2c8
Create Date: 2025-12-28 11:23:22.947154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af4d6b1b4ef0'
down_revision: Union[str, None] = '62969964c2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    pass


def downgrade_source() -> None:
    pass


def upgrade_market() -> None:
    pass


def downgrade_market() -> None:
    pass


def upgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sourcing_recommendations', sa.Column('option_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sourcing_recommendations', 'option_recommendations')
    # ### end Alembic commands ###
