"""initial_split_schema

Revision ID: b6a6cd68987c
Revises: 
Create Date: 2025-12-17 13:38:46.935166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

revision: str = 'b6a6cd68987c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code', 'username', name='uq_supplier_accounts_supplier_username')
    )
    op.create_table('supplier_category_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code', 'category_id', name='uq_supplier_category_raw_supplier_category')
    )
    op.create_table('supplier_item_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('item_code', sa.Text(), nullable=True),
    sa.Column('item_key', sa.Text(), nullable=True),
    sa.Column('item_id', sa.Text(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code', 'item_code', name='uq_supplier_item_raw_supplier_item_code'),
    sa.UniqueConstraint('supplier_code', 'item_key', name='uq_supplier_item_raw_supplier_item_key')
    )
    op.create_table('supplier_order_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code', 'account_id', 'order_id', name='uq_supplier_order_raw_supplier_account_order')
    )
    op.create_table('supplier_qna_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('qna_id', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code', 'account_id', 'qna_id', name='uq_supplier_qna_raw_supplier_account_qna')
    )
    op.create_table('supplier_raw_fetch_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_sync_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('sync_type', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('watermark_ms', sa.BigInteger(), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code', 'sync_type', 'account_id', name='uq_supplier_sync_state_supplier_type_account')
    )
    # ### end Alembic commands ###


def downgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_sync_state')
    op.drop_table('supplier_sync_jobs')
    op.drop_table('supplier_raw_fetch_log')
    op.drop_table('supplier_qna_raw')
    op.drop_table('supplier_order_raw')
    op.drop_table('supplier_item_raw')
    op.drop_table('supplier_category_raw')
    op.drop_table('supplier_accounts')
    # ### end Alembic commands ###


def upgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_item_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('processed_name', sa.Text(), nullable=True),
    sa.Column('processed_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sourcing_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('supplier_item_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('supply_price', sa.Integer(), nullable=False),
    sa.Column('source_strategy', sa.Text(), nullable=False),
    sa.Column('benchmark_product_id', sa.UUID(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('seasonal_score', sa.Float(), nullable=True),
    sa.Column('margin_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('spec_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seo_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_event', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sourcing_candidates')
    op.drop_table('products')
    op.drop_table('embeddings')
    op.drop_table('api_keys')
    # ### end Alembic commands ###


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_collect_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('markets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('failed_markets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_html', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_summary', sa.Text(), nullable=True),
    sa.Column('pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'product_id', name='uq_benchmark_products_market_product')
    )
    op.create_table('market_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'name', name='uq_market_accounts_code_name')
    )
    op.create_table('supplier_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('supplier_order_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('market_account_id', sa.UUID(), nullable=False),
    sa.Column('market_item_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_account_id'], ['market_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_account_id', 'market_item_id', name='uq_market_listings_account_item')
    )
    op.create_table('market_order_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['market_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'account_id', 'order_id', name='uq_market_order_raw_account_order')
    )
    op.create_table('market_product_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('market_item_id', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['market_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'account_id', 'market_item_id', name='uq_market_product_raw_account_item')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_order_id', sa.UUID(), nullable=True),
    sa.Column('supplier_order_id', sa.UUID(), nullable=True),
    sa.Column('order_number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('recipient_name', sa.Text(), nullable=True),
    sa.Column('recipient_phone', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_order_id'], ['market_order_raw.id'], ),
    sa.ForeignKeyConstraint(['supplier_order_id'], ['supplier_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('market_product_raw')
    op.drop_table('market_order_raw')
    op.drop_table('market_listings')
    op.drop_table('supplier_orders')
    op.drop_table('market_accounts')
    op.drop_table('benchmark_products')
    op.drop_table('benchmark_collect_jobs')
    # ### end Alembic commands ###
