"""add_strategy_id_to_recommendation

Revision ID: e71f7fbc1788
Revises: a68774858fac
Create Date: 2025-12-31 17:37:25.678384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e71f7fbc1788'
down_revision: Union[str, None] = 'a68774858fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_recommendations', sa.Column('strategy_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_recommendations', 'strategy_id')
    # ### end Alembic commands ###
