"""Add pricing strategy and category mapping models

Revision ID: e8497b8fb116
Revises: 4bc94d14e253
Create Date: 2025-12-31 17:11:43.427613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8497b8fb116'
down_revision: Union[str, None] = '4bc94d14e253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_source() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('strategy_id', sa.UUID(), nullable=True, comment='수동 할당된 가격 전략 ID (Cross-DB: No FK)'))
    # ### end Alembic commands ###


def downgrade_dropship() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'strategy_id')
    # ### end Alembic commands ###


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target_margin', sa.Float(), nullable=False),
    sa.Column('min_margin_gate', sa.Float(), nullable=False),
    sa.Column('max_price_delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category_strategy_mappings',
    sa.Column('category_code', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['pricing_strategies.id'], ),
    sa.PrimaryKeyConstraint('category_code')
    )
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_strategy_mappings')
    op.drop_table('pricing_strategies')
    # ### end Alembic commands ###
