"""add_product_processing_fields

Revision ID: f3779c243ce9
Revises: 686efadceb0f
Create Date: 2025-12-15 20:06:40.589069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f3779c243ce9'
down_revision: Union[str, None] = '686efadceb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('processed_name', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('processed_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('processed_image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('processing_status', sa.Text(), nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'processing_status')
    op.drop_column('products', 'processed_image_urls')
    op.drop_column('products', 'processed_keywords')
    op.drop_column('products', 'processed_name')
    # ### end Alembic commands ###
