"""add_market_fee_policy

Revision ID: f3dfc67b9b8b
Revises: af4d6b1b4ef0
Create Date: 2025-12-28 12:09:14.581811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

revision: str = 'f3dfc67b9b8b'
down_revision: Union[str, None] = 'af4d6b1b4ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "") -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_source() -> None:
    pass


def downgrade_source() -> None:
    pass


def upgrade_dropship() -> None:
    pass


def downgrade_dropship() -> None:
    pass


def upgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_fee_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_code', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Text(), nullable=True),
    sa.Column('fee_rate', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'category_id', name='uq_market_fee_policies_market_category')
    )
    # ### end Alembic commands ###


def downgrade_market() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_fee_policies')
    # ### end Alembic commands ###
